name: Documentation
on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.8'
      - name: Install dependencies
        run: |
           using Pkg 
           Pkg.add("Documenter")
           Pkg.develop(PackageSpec(path=pwd()))
           Pkg.instantiate()
        shell: julia --project=docs/ -e
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
        run: docs/make.jl
        shell: julia --project=docs/ --color=yes {0}